const systemFontStack = [
  "system-ui",
  "-apple-system",
  "BlinkMacSystemFont",
  '"Segoe UI"',
  "Roboto",
  '"Helvetica Neue"',
  "Arial",
  '"Noto Sans"',
  "sans-serif",
  '"Apple Color Emoji"',
  '"Segoe UI Emoji"',
  '"Segoe UI Symbol"',
  '"Noto Color Emoji"',
];

module.exports = {
  theme: {
    fontFamily: {
      body: ['"Open Sans"', ...systemFontStack],
      display: ["Montserrat", ...systemFontStack],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        '"Liberation Mono"',
        '"Courier New"',
        "monospace",
      ],
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1670px",
    },
    extend: {
      width: {
        9: "2.25rem",
        11: "2.75rem",
        26: "6.5rem",
        36: "8.5rem",
        88: "22rem",
        "fit-content": "fit-content",
      },
      minWidth: {
        6: "1.5rem",
        28: "7rem",
        30: "7.5rem",
        34: "8.5rem",
        48: "12rem",
      },
      minHeight: {
        40: "10rem",
        96: "44rem",
        128: "32rem",
        192: "48rem",
      },
      maxWidth: {
        176: "44rem",
        "3/5": "60%",
      },
      maxHeight: {
        32: "8rem",
        40: "10rem",
        132: "33rem",
      },
      height: {
        9: "2.25rem",
        11: "2.75rem",
        76: "19rem",
        160: "40rem",
        "fit-content": "fit-content",
      },
      borderWidth: {
        1: "1px",
        5: "5px",
      },
      margin: {
        "1/2": "0.125rem",
        "1/4": "0.0625rem",
      },
      inset: {
        2: "0.5rem",
        "1/2": "50%",
        full: "100%",
      },
    },
    colors: {
      transparent: "transparent",
      inherit: "inherit",
      primary: "#1679a4",
      secondary: "#4a5b64",
      white: "#fff",
      black: "#000",
      green: "#35b536",
      "dark-green": "#468847",
      orange: "#f89406",
      blue: "#1d8dc4",
      "dark-orange": "#f74f07",
      red: "#d42d2a",
      "dark-red": "#6e100e",
      grey: {
        100: "#000",
        200: "#0c0c0c",
        300: "#1b1f21",
        400: "#2d3436",
        500: "#636d73",
        600: "#575d5e",
        700: "#999",
        800: "#c7d1d6",
        900: "#fff",
      },
      risk: {
        0: "#35b536",
        1: "#468847",
        2: "#999999",
        3: "#f89406",
        4: "#1d8dc4",
        5: "#f74f07",
        6: "#d42d2a",
        7: "#6e100e",
      },
      unknown: "#ff00ef",
      "unknown-alt": "#0010ff",
    },
    customForms: (theme) => ({
      default: {
        "input, textarea, select, multiselect": {
          backgroundColor: theme("colors.grey.400"),
          borderColor: theme("colors.grey.400"),
          '[data-theme="light"] &': {
            backgroundColor: theme("colors.white"),
            borderColor: theme("colors.grey.800"),
          },
        },
      },
    }),
  },
  variants: {
    margin: ["responsive", "first", "last"],
    textColor: [
      "responsive",
      "hover",
      "focus",
      "focus-within",
      "group-hover",
      "light",
      "light-hover",
    ],
    backgroundColor: [
      "responsive",
      "hover",
      "focus",
      "focus-within",
      "group-hover",
      "light",
      "light-hover",
      "checked",
    ],
    borderWidth: [
      "responsive",
      "hover",
      "focus",
      "focus-within",
      "group-focus-within",
      "group-hover",
      "light",
      "light-hover",
      "first",
      "last",
    ],
    borderColor: [
      "responsive",
      "hover",
      "focus",
      "focus-within",
      "group-focus-within",
      "group-hover",
      "light",
      "light-hover",
      "light-focus",
    ],
    boxShadow: [
      "responsive",
      "hover",
      "focus",
      "active",
      "group-hover",
      "group-focus-within",
    ],
    borderRadius: ["responsive", "first", "last"],
    display: ["responsive", "group-focus-within", "group-hover", "light"],
  },
  plugins: [],
  corePlugins: {
    container: false,
  },
  purge: {
    content: ["./src/**/*.html", "./src/**/*.component.ts"],
    options: {
      whitelistPatterns: [],
    },
  },
  future: {
    removeDeprecatedGapUtilities: true,
  },
};
